# Basic Settings for the plugin
# Set "enabled" to false if you have a different plugin for spawn-handle
Spawn:
    enabled: true
    x: 0
    y: 100
    z: 0
    yaw: 0
    pitch: 0
    world: world
    
# The duration of the combat log (if set to 0, the plugin won't use it's own combatlog system)
CombatLogDuration: 15

# This is the global scoreboard that will be shown to players
# that aren't in an arena/their arena doesn't have a scoreboard!
Scoreboard:
    Enabled: true
    Title: "   &e&lArmsRace   "
    Footer: "&ewww.spigotmc.org"
    Lines:
    - " "
    - "&fName: &a%name%"
    - "&fDisplay Name: &a%displayname%"
    - "  "
    - "&fKills: &a%sumkills%"
    - "&fDeaths: &a%sumdeaths%"
    - "&fCoins: &a%coins%"
    - "   "
    
# Settings of pickups - Items & names
Pickups:
    Healing:
        Item: EMERALD_BLOCK
        Name: "&aHealing"
    DoubleDamage:
        Item: REDSTONE_BLOCK
        Name: "&cDouble Damage"
    Coins:
        Item: GOLD_BLOCK
        Name: "&6Coins"
    Speed:
        Item: IRON_BLOCK
        Name: "&fSpeed"
    Resistance:
        Item: DIAMOND_BLOCK
        Name: "&4Resistance"
    TierUp:
        Item: ARROW
        Name: "&6Tier Up"
    OneTap:
        Item: DIAMOND_SWORD
        Name: "&eOne Tap"
        
# Settings of skills
Skills:
    SwordLaunch:
        CooldownSeconds:
            1: 60
            2: 55
            3: 50
            4: 45
    HeadShot:
        # Rate is in % (1-100)
        Rate:
            1: 1
            2: 2
            3: 3
            4: 4
    ExtraGold:
        Amount:
            1: 2
            2: 4
            3: 6
            4: 8
            5: 10
    SkipTier:
        # Rate is in % (1-100)
        Rate:
            1: 1
            2: 2
            3: 3
    SpawnResistance:
        DurationSeconds:
            1: 3
            2: 5
            3: 8
            4: 10
    ExtraHealth:
        # 1 = half heart.
        Amount:
            1: 2
            2: 4
            3: 6
    SpawnGapple:
        # Rate is in % (1-100)
        Rate:
            1: 1
            2: 2
            3: 3
            4: 4
            5: 5
# Settings of trails
# * speed = ticks (1 second = 20 ticks)
Trails:
    Amount: 2
    Speed: 3